nama = input("Nama  : ")
email = input("Email    : ")
jabatan = input("Jabatan    : ")
umur = input("Umur  : ")
print("=============OUTPUT==============")
print("Nama : ", nama)
print("Email : ", email)
print("Jabatan : ", jabatan)
print("Umur : ", umur)